# Generated by Django 3.2.18 on 2023-03-27 03:54

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='n/a', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='n/a', max_length=63),
        ),
        migrations.AddField(
            model_name='post',
            name='profession',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
