# Generated by Django 3.2.18 on 2023-04-04 05:38

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230328_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='carousel_images',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profession',
            field=models.CharField(default='n/a', max_length=80),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='display_services',
            field=models.ManyToManyField(blank=True, to='booking.Service'),
        ),
    ]
