# Generated by Django 3.2.18 on 2023-04-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20230404_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='business_owner',
        ),
    ]
