# Generated by Django 3.2.18 on 2023-04-07 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0005_rename_title_post_business_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.CharField(choices=[('A', '9:00-10:00'), ('B', '10:00-11:00'), ('C', '11:00-12:00'), ('D', '12:00-13:00'), ('E', '13:00-14:00'), ('F', '14:00-15:00'), ('G', '15:00-16:00'), ('H', '16:00-17:00')], default='A', max_length=2)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.post')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
